[package]
name = "typo-fixer"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.25"
objc = "0.2"
core-foundation = "0.10"
core-graphics = "0.24"
accessibility-sys = "0.1"
libc = "0.2"
global-hotkey = "0.4"
# llama-cpp-2 = "0.1.54"  # Keep disabled for testing
once_cell = "1.19"
toml_edit = { version = "0.22", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"

[dev-dependencies]
tempfile = "3.10"

[profile.release]
opt-level = 3
strip = true
lto = true

[[bin]]
name = "typo-fixer"
path = "src/main.rs"